---
manifests:
  - release-name: elastic-runtime  # pivnet release 1.6.16
    deployment-name: elastic-runtime
    release-number: "2134"
    file-number: "5888"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent?v=3232.17"
    file: elastic-runtime.yml
    errands:
     - smoke-tests
     - push-apps-manager
     - autoscaling
     - autoscaling-register-broker

  - release-name: p-mysql
    deployment-name: p-mysql
    release-number: "1770"
    file-number: "4696"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent"
    file: p-mysql.yml
    errands:
     - broker-registrar

  - release-name: pivotal-rabbitmq-service
    deployment-name: p-rabbitmq
    release-number: "1799"
    file-number: "4766"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent"
    file: p-rabbitmq.yml
    errands:
     - broker-registrar

  - release-name: p-redis
    deployment-name: p-redis
    release-number: "1876"
    file-number: "4965"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent"
    file: p-redis.yml
    errands:
     - broker-registrar


  - release-name: p-spring-cloud-services
    deployment-name: p-spring-cloud-services
    release-number: "1735"
    file-number: "4527"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent"
    file: p-spring-cloud-services.yml
    errands:
      - deploy-service-broker
      - register-service-broker

  - release-name: concourse
    deployment-name: concourse
    release-number: "1.6.0"
    file-number: "0"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent"
    file: concourse.yml
