---
manifests:
  - release-name: elastic-runtime  # pivnet release 1.6.16
    deployment-name: elastic-runtime
    release-number: "1485"
    file-number: "3888"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent"
    file: elastic-runtime-premium.yml
    errands:
     - smoke-tests
     - push-apps-manager
     - push-app-usage-service
     - autoscaling
     - autoscaling-register-broker

  - release-name: p-mysql
    deployment-name: p-mysql
    release-number: "1509"
    file-number: "3930"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent"
    file: p-mysql-premium.yml
    errands:
     - broker-registrar

  - release-name: pivotal-rabbitmq-service
    deployment-name: p-rabbitmq
    release-number: "1523"
    file-number: "3962"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent"
    file: p-rabbitmq-premium.yml
    errands:
     - broker-registrar

  - release-name: p-redis
    deployment-name: p-redis
    release-number: "1506"
    file-number: "3928"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent"
    file: p-redis-premium.yml
    errands:
     - broker-registrar
     - smoke-tests

  - release-name: p-spring-cloud-services
    deployment-name: p-spring-cloud-services
    release-number: "1524"
    file-number: "3963"
    stemcell: "https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent"
    file: p-spring-cloud-services-premium.yml
    errands:
      - deploy-service-broker
      - register-service-broker
